version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  nginx_static_files: {}
services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/staging/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./compose/staging/nginx:/etc/nginx/conf.d
      - nginx_static_files:/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - django

  postgres:
    image: postgres:12-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
  redis:
    image: redis:6-alpine

  channels:
    <<: *django
    image: freelanium_channels
    command: daphne -b 0.0.0.0 -p 8001 config.asgi:application
    ports:
      - 8001:8001

  celeryworker:
    <<: *django
    image: freelanium_staging_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: freelanium_staging_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: freelanium_staging_flower
    ports:
      - "5555:5555"
    command: /start-flower
