version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:12-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .env

  redis:
    image: redis:6-alpine

  celeryworker:
    <<: *django
    image: freelanium_local_celeryworker
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: freelanium_local_celerybeat
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: freelanium_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
