# Generated by Django 3.0.3 on 2021-04-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
