# Generated by Django 3.0.3 on 2021-04-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
