# Generated by Django 3.0.3 on 2021-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210328_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('NO', 'Normal order'), ('TP', 'Two payments order'), ('RO', 'Recurrent order')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('NO', 'Normal order'), ('TP', 'Two payments order'), ('RO', 'Recurrent order')], max_length=2),
        ),
    ]
