# Generated by Django 3.0.3 on 2021-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210331_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('HO', 'Holding payment order'), ('TP', 'Two payments order'), ('RO', 'Recurrent order')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('HO', 'Holding payment order'), ('TP', 'Two payments order'), ('RO', 'Recurrent order')], max_length=2),
        ),
    ]
