# Generated by Django 3.0.3 on 2021-04-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210405_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer', name='type', field=models.CharField(
                choices=[('OP', 'One payment order'),
                         ('HO', 'Holding payment order'),
                         ('TP', 'Two payments order'),
                         ('RO', 'Recurrent order')],
                max_length=2),),
        migrations.AlterField(
            model_name='order', name='type', field=models.CharField(
                choices=[('OP', 'One payment order'),
                         ('HO', 'Holding payment order'),
                         ('TP', 'Two payments order'),
                         ('RO', 'Recurrent order')],
                max_length=2),), ]
