name: Freelanium site CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env: ./envs/.prod/.*
      - name: Build the site api.freelanium.com
        run: ./deploy.sh
