name: Freelanium site CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the site api.freelanium.com
        with:
          context: ./
      - name: Run the docker compose script
        run: ./deploy.sh
