name: Freelanium site CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the site api.freelanium.com
        run: docker-compose -f ${{ github.workspace }}docker-compose.prod.yml build && docker-compose -f ${{ github.workspace }}docker-compose.prod.yml down && supervisorctl restart freelanium
